name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Create config file
        run: |
          echo "const config = {" > config.js
          echo "    LASTFM_API_KEY: '${{ secrets.LASTFM_API_KEY }}'," >> config.js
          echo "    LASTFM_USERNAME: '${{ secrets.LASTFM_USERNAME }}'" >> config.js
          echo "};" >> config.js

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Build with Jekyll
        uses: "ghcr.io/actions/jekyll-build-pages:v1.0.13"
        with:
          source: ./
          destination: ./_site

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4